apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: phpmyadmin-http-ingress
spec:
  rules:
  - host: pma.docker.local
  backend:
    serviceName: phpmyadmin-service
    servicePort: 80
