apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wordpress-http-ingress
spec:
  rules:
  - host: wordpress.docker.local
  backend:
    serviceName: wordpress-service
    servicePort: 80
