apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-http-ingress
spec:
  rules:
  - host: wordpress.cluster.local
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress-service
          servicePort: 80
